### PR TITLE
Include Blockpool and Kapu by default

### PR DESCRIPTION
**Pull request by balubalubalu**
This is the list of the implemented changes:
- Move the config info of the networks to a config file.
- Implement changes to include the network of blockpool and Kapu to the menu automatically
- Implement the way to refresh the menu with new networks every time we add a new one in the config file.

Solves https://github.com/ArkEcosystem/ark-desktop/issues/484

### CODE REVIEW

**Comment by j-a-m-l** [comment]
@Jarunik any more network?

**Comment by Jarunik** [comment]
I think the two are fine for now to have the live once.

**Comment by luciorubeens** [comment]
This PR is controversial, need to discuss before merge. I think it is not a good option, only devnet already confuses users.

**Comment by boldninja** [comment]
I have to agree with @luciorubeens what happens once there are 20-30 forks of ARK? I'd move this custom forks into a kind of "folder" in manage networks and if you click there would be a list of all avail forks and when you click on it will ask you if you want to get it added to the list.

**Comment by alexbarnsley** [comment]
What if we have a marketplace somewhere like networks.ark.io, where there's a link to their own homepage plus a link to load the network into the desktop application through a custom URI scheme? 🤔

**Comment by fix** [comment]
I would not do that, because 
- it would look too complex for users
- would let think that blockpool, kapu or others a under quality ark blockchain


Instead we should think about something that would make the blockchain some first class citizen
somehow.

maybe some kind of build config that would make easy to compile a kapu desktop client.

or a "first start" welcome screen to choose default blockchain you are in, and hiding the others into some "advanced user" settings

**Comment by j-a-m-l** [comment]
Yes, choosing the blockchain at the beginning would be probably the best way to make them "first class citizens".

What do you think about using a grid like the appearance dialogue with the name of the blockchain, an (optional) image, and a description and or link to its website? It would be used to change blockchain / network instead of the current dropdown.

As a reference:
appearance

**Comment by j-a-m-l** [comment]
@fix @luciorubeens @alexbarnsley @boldninja any new feedback?

**Comment by alexbarnsley** [comment]
@j-a-m-l I like the idea of a market place, either when first opening or an option in the menu to view "Network Marketplace". I think it needs to be easier for users to add a new network, without having to know IPs, etc. But we also can't be hardcoding each sidechain into the repo. Perhaps this PR should be closed and the discussion carries on on #484

**Pull request closed without merging**
