### PR TITLE
More User Friendly

### PR DESCRIPTION
**Pull request by mody199610**
Changed the cold wallet message to a more friendly one that wont confuse ARK Users.

### CODE REVIEW

**Comment by mody199610** [comment]
#83 Done @fix

**Comment by boldninja** [comment]
This account has never had any transactions yet. 
Hm I think this could also be confusing to people who have transactions in that address, but no tx out.

**Comment by dafty-1** [comment]
Do we need a message at all? The people who know what a cold wallet is would already know that it's a cold wallet, and the people who don't know get totally spooked by it.

If this is about the address not appearing on any explorers, then perhaps it should be changed to say that instead, in simple terms.

**Comment by zillionn** [comment]
Or something like:
This is an offline savings wallet (cold wallet). To make it visible online, you need to send some funds.

**Comment by fix** [comment]
Well technically a cold wallet is a wallet that never SENT a transaction. A cold wallet technically is a wallet which public key is unknown. It will be known when the first transaction OUT is recorded on the blockchain.

**Comment by mody199610** [comment]
True @fix however we'd need a more friendly message to appear since any new crypto user would freak out if his funds got to his wallet a bit late

**Comment by boldninja** [comment]
@mody199610 cold wallet will stay cold even if you send Ark in it - it only changes from cold to hot once its been used for TX out .

**Comment by dafty-1** [comment]
My understanding of a cold wallet is an address created offline and maintained offline until you create and broadcast a transaction using any machine. If the machine used to send the tx is connected to the internet and has the passphrase typed in, it becomes hot.

What if you generated a transaction offline using the passphrase and then broadcasted it from a separate machine? In my opinion the wallet is still cold?

What I'm trying to say is I don't think cold wallet is the right terminology. It depends on how the wallet was set up and maintained. Saving the passphrase on a library PC doesn't make it cold just because a tx hasn't been sent out yet?

**Comment by zillionn** [comment]
I believe this message is for non-technical people, so it doesn't matter if it's technically correct. You could just write:
Cold wallet. No outbound transactions yet.

**Comment by fix** [comment]
@zillionn sounds good to me. @mody199610 can you update your PR with this?

**Comment by mody199610** [comment]
@fix  Done :)

**Comment by fix** [comment]
+5

**Pull request merged**
