### PR TITLE
Fix Theming issues.

### PR DESCRIPTION
**Pull request by ckhatri**
If you clicked add contact through the main menu so settings -> Add Contact. The theme would be broken and set to default. It worked normally through the sidenav -> Add Contact though.

Noticed that if you did main-navbar, ul would be undefined. Now fixed!

Also fixed the sign and verify pages as well in a later commit.

### CODE REVIEW

**Comment by alexbarnsley** [comment]
@ckhatri I can't seem to replicate the issue with the theme. I tried the steps above but still seems to work okay for me. Would you mind doing a gif please? :)

**Comment by ckhatri** [comment]
@alexbarnsley 

here ya go: https://gfycat.com/ScarceTautAstarte

**Comment by alexbarnsley** [comment]
@ckhatri did you get round to taking a look at @j-a-m-l's suggestions? 😄

**Comment by alexbarnsley** [comment]
Closing due to lack of a response.

**Pull request closed without merging**
