### PR TITLE
Fix ledger device list blocking call on certain systems

### PR DESCRIPTION
**Pull request by hmmdeif**
Fixes [#263](https://github.com/ArkEcosystem/ark-desktop/issues/263#issuecomment-329732163).

### CODE REVIEW

**Comment by fix** [comment]
is this fixing the issue on your platform?

**Comment by hmmdeif** [comment]
Yes. It will be worth finding someone with a ledger to check that it still works for them though.

**Comment by boldninja** [comment]
I can test ledger on Win 8.1 x64 if @fix can compile for me.

**Comment by fix** [comment]
@boldninja you can compile i guess.
- clone the repo
- npm install
- npm start

**Comment by fix** [comment]
so won't work, because the message sent is json, not an object to be manipulated later on

**Comment by hmmdeif** [comment]
Of course, makes sense. I should've seen the function calls further down.

**Comment by fix** [comment]
@hmmdeif no pb i have changed your PR, working now, can you check master now?

https://github.com/ArkEcosystem/ark-desktop/pull/268

**Comment by hmmdeif** [comment]
Yep it's all responsive for me!

**Comment by boldninja** [comment]
@hmmdeif can you provide me with your ark address?

**Comment by hmmdeif** [comment]
@boldninja APNSuVmJjg6K32XHSQQ6e4H7jDDm1LfpWj

**Pull request closed without merging**
