### PR TITLE
[Lint] Format code

### PR DESCRIPTION
**Pull request by noahgr**
Hi, i formatted the code using the standardjs, this is a lot of changes but I just removed the spaces, the semicolons and other minor changes. So do not worry about merging this or validating each line.. Cheers!

### CODE REVIEW

**Comment by alexbarnsley** [comment]
I wish I could explain why no semi-colons bothers me so much. I know it's a standard but it just doesn't feel right 😂

**Comment by noahgr** [comment]
@alexbarnsley I've the same feeling, unfortunately it's the standard :cry:

**Comment by alexbarnsley** [comment]
😩

im-not-mad-just-disappointed

**Comment by luciorubeens** [comment]
Hmm it seems that nobody here wants to remove the semicolons, I think that instead of the standardjs we can use the eslint with our rules..

**Comment by boldninja** [comment]
Oh look at the boys making their own standards who is cool now

semicolumn

**Comment by alexbarnsley** [comment]
I did find this when trying to find out why get rid of semicolons in case anyone is interested: https://github.com/Flet/semistandard

@boldninja leave the developers to talk important things 😂

**Comment by krau612** [comment]
Not the semicolons! :sob: 

jk I actually don't mind getting rid of them lol

**Comment by j-a-m-l** [comment]
I don't care too much about using 1 style or another, but semicolons are almost useless, so why adding them when it's not necessary?
 - http://inimino.org/~inimino/blog/javascript_semicolons
 - http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding
 - https://www.youtube.com/watch?v=gsfbh17Ax9I

**Comment by zillionn** [comment]
Because you're used to use semicolons when you write in other languages.

**Comment by alexbarnsley** [comment]
Agree with @zillionn, there are more languages with a semi than not. For me as well (yes preference), a semi colon visually tells the developer it's the end of a statement. 

I'm all for a standard and keeping everything consistent though, and will get used to whatever is used

**Comment by j-a-m-l** [comment]
@zillionn I'm used to languages that don't use semicolons (Ruby, Python...) so to me and more people that isn't a valid argument because different people have different background. So the standard should be for JS only, not thinking about other languages.

For me, an argument that is independent of the personal background would be @alexbarnsley position. But I think that it has a big flaw, because all JS developers know that the end of a line is visually the end of the statement, so adding a `;` at the end of the line doesn't add any special meaning.

IMHO it's just a reminiscence of the times when JS developers didn't know how to use them (http://inimino.org/%7Einimino/blog/javascript_semicolons).

Of course, it's impossible to create a standard that all people love, so maybe it's better to use 1 that it's used in more projects although we don't like all their decisions (I don't like several of them), than creating a new one and discussing about our personal preferences.

**Comment by zillionn** [comment]
That was just my opinion. I don't have much time to contribute so it's not up to me. Probably the people who contribute most should decide which standard to use.

**Comment by luciorubeens** [comment]
"Are we going to perpetuate this misleading tradition?" :joy:

@j-a-m-l Ok, you convinced me. Let's get used!

semicolon

@noahgr +5! 👍🏻

**Comment by alexbarnsley** [comment]
That meme 😂

**Comment by j-a-m-l** [comment]
I've to admit that the real reason for using StandardJS is adding a badge...

StandardJS

**Pull request merged**
