### PR TITLE
Show remaining balance on the sendArk view

### PR DESCRIPTION
**Pull request by 6ea86b96**
For issue #60 

First time using Angular. Maybe there's a better way?

### CODE REVIEW

**Comment by fix** [comment]
nice use of big number, we should generalise on the whole app.

**Comment by Doweig** [comment]
Adding a new module for this feature is a bit overkill.
There's a snippet that already do the same formatting on the transactions objects here https://github.com/ArkEcosystem/ark-desktop/blob/master/client/app/src/accounts/AccountService.js#L237
Just need to use this snippet for account, like a "humanTotal" field

**Comment by fix** [comment]
@doweig can you close this if needed then? or do we needs an update to the PR?

**Comment by mattbeedle** [comment]
Ah, cool, sorry, didn't see there was already a snippet for that @Doweig. I agree, definitely not worth a module.

**Comment by fix** [comment]
closing PR but giving +5 for the work. Thanks!

**Comment by boldninja** [comment]
@mattbeedle and @6ea86b96 can you both provide me with your Ark address for +5 ARK where you want them sent.

**Pull request closed without merging**
