### PR TITLE
Added new terms and adjusted others

### PR DESCRIPTION
**Pull request by luciorubeens**
Update language pt_BR.

### CODE REVIEW

**Comment by fix** [comment]
nice one, could you head towards https://osjc1wl.oneskyapp.com/collaboration/project?id=95031 for  BR translations?

**Comment by fix** [comment]
+5

**Comment by boldninja** [comment]
@luciorubeens hi Lucio - can you provide me with you ARK address on which I'll provide any +5 ARK payments and monthly ones as well ( if you don't have an address https://blog.ark.io/how-to-generate-your-own-ark-address-and-passphrase-5e4e1257ca5e  )- this accepted pull will also count towards May monthly rewards. Thank you for your work.

**Comment by luciorubeens** [comment]
@fix cool, i will signup now

**Comment by luciorubeens** [comment]
@boldninja i think the reward would be sent to slack arkbot tip, but send for this address: AaeUXmGKG1GRsCEZrBzsBfBs2sEx4z5ozu. Thx!

**Comment by boldninja** [comment]
I'd much prefer to send them to the account you hold private key to if you get any larger rewards (like monthly or some others) . I'll put it in my spreadsheet - if you want it changed to some other address in the future just let me know. Will start paying those +5 out this week and all requested accepted from today onwards will will count towards May as well.

**Comment by luciorubeens** [comment]
@boldninja Oh no, 3/6 PRs were requested in 30/03, please consider my participation in Apr too. No problem if i dont win, i will continue contributing this month.

**Pull request merged**
