### PR TITLE
Standardized menu and shortcut to match the system’s

### PR DESCRIPTION
**Pull request by gabrielbull**
Fixes issue #557 and standardizes application's menu to match the system.

<sub><sub><sub>My own approval.</sub></sub></sub>
&nbsp;&nbsp;&nbsp;&nbsp;↓

### CODE REVIEW

**Comment by alexbarnsley** [comment]
Nice! I do like/prefer how this is done. I will try and test later on if I get chance (don't usually work weekends)

**Comment by alexbarnsley** [comment]
Oh, could you fix the build errors please. Complaining about unused `globalShortcut`. Thanks!

**Comment by gabrielbull** [comment]
Done

**Comment by j-a-m-l** [comment]
@alexbarnsley Could you review it? (I don't have OSX)

**Comment by alexbarnsley** [comment]
@gabrielbull I like how this all works. However, Cmd + H doesn't hide the window like it used to with my High Sierra OS.

**Comment by gabrielbull** [comment]
@alexbarnsley That's weird, it works fine for me. On macOS, you cannot hide an application if it is the only application visible. You can try this with any other application, like Safari, try to hide all other applications with ⌥⌘H and then try to hide Safari with ⌘H, it will not hide. Have you made sure that Ark is not the only visible application? Make sure you see another's application window and Ark's window at the same time.

**Comment by alexbarnsley** [comment]
Don't worry. I think it'll be an issue with my setup (i've probably got something controlling keyboard shortcuts). It doesn't work on Chrome either as you say, and i have loads of windows open. The menu shows ⌘H as the shortcut.

I was happy other than this, and blaming my setup! Thanks! 👍

**Comment by boldninja** [comment]
@gabrielbull provide me with your ARK address or contact me on Ark slack (boldninja) if you don't want to share it publicly.

**Comment by gabrielbull** [comment]
88/A/U

**Pull request merged**
