### PR TITLE
Address on type checks in send dialog

### PR DESCRIPTION
**Pull request by Nasicus**
We now have the following states:

Invalid Address (error, send is disabled):

Address is own address (warning, send is enabled):

Address doesn't have any transaction / doesn't exist (info, send is enabled):

Address is neo address (warning, send is enabled):
=> should we display it as an error or as a warning? (and disable send button) I think warning is correct.

... and of course, the state when everything is fine:

Addresses: #489

### CODE REVIEW

**Comment by fix** [comment]
well done @Nasicus for this NEO address pinging

What i am not sure is if same publickey gives same address, if yes i guess we could lock down the 'send' button if a NEO address is matched

**Comment by Nasicus** [comment]
@fix 
Thanks.
Even if it would: Wouldn't the possibility of generating the same address be impossible small anyway? If so you're right and showing and error + disabling the button would be better.

(Will resolve the conflicts this evening)

**Comment by luciorubeens** [comment]
NEO uses elliptic curve secp256r1, and ARK uses secp256k1. So the private key will be different.

**Comment by Nasicus** [comment]
But getting the same addresses should still be nearly impossible?  (Sorry I'm not really "educated" in this whole area :) )
And what does this mean concerning if it should be `warning` or an `error`? :D

**Comment by luciorubeens** [comment]
Well, they use a different mechanism, so the same publicKey will generate different addresses. But yes, it's possible to have the same address in both blockchains. Looks good, good job! :+1:

**Pull request merged**
