### PR TITLE
Fix message warning in createAccount

### PR DESCRIPTION
**Pull request by yagoantonio**

### CODE REVIEW

**Comment by luciorubeens** [comment]
+5

**Comment by boldninja** [comment]
@yagoantonio Ark address still same for bounty?

**Comment by yagoantonio** [comment]
yes @boldninja 
Just to confirm: AYYAeqjcZmwBzVab13REoPiZDrXtYGifQW
Tks!

**Comment by boldninja** [comment]
Sent @yagoantonio keep up the good work in September as well.

**Comment by yagoantonio** [comment]
tks!
You can count on me!

**Pull request merged**
