### PR TITLE
make installation easier and quicker

### PR DESCRIPTION
**Pull request by bitcoinsSG**

### CODE REVIEW

**Comment by fix** [comment]
sounds good to me, what do you thing @Doweig ? it would replace #63 imo

**Comment by bitcoinsSG** [comment]
Does is usually take a while for pull request approvals? I did not follow any process as I couldn't find one for submitting pull requests. Is there a publicly available approval process / protocol one can use as a reference so as not to prolong due to not satisfying prerequisites?

**Comment by fix** [comment]
yo sorry, @doweig is moving away from taking care of the repo since he is starting a business. I am taking over the responsability for now. Sorry for delays

**Comment by boldninja** [comment]
@bitcoinsSG can you provide me with your permanent ARK address for +5 ARK accepted pulls and any other github rewards..

**Comment by bitcoinsSG** [comment]
@boldninja thank you for this! may I respectfully ask to use the +5 ARK for someone else's successful pull request ? Would like to reserve incentives to others who may not be inclined to contribute pro bono. Thank you again.

**Comment by boldninja** [comment]
@bitcoinsSG as you wish - I'll donate to Ark Community Fund for them to use in your name if you wish so? Thank you for contributions and helping out - much appreciated.

**Comment by bitcoinsSG** [comment]
@boldninja that's even better. thanks.

**Pull request merged**
