### PR TITLE
Bug fixes & changes in manage networks

### PR DESCRIPTION
**Pull request by Nasicus**
- check for required fields when adding / updating networks
- make almost all fields required when updating network
- don't open an invalid URL if explorer of a network is not specified

As mentioned I made almost all field in mange network required, but imho this makes sense, correct me if I'm wrong:
image

Fixes: #559, #571

### CODE REVIEW

**Comment by alexbarnsley** [comment]
Looks good - not tested yet as had 1 possible change. Maybe in the canCreate and canUpdate methods, add a check for the URL always having "http://" or "https://". I don't think it works at all without either. Maybe a URL validator of some sort, `http://1.2.3.4:1234` = valid; `http://1.2.3.4:` = invalid, etc

**Comment by Nasicus** [comment]
Right. I wanted to to that but forgot again.
Where would you show when the URL is valid? as a toast and leave the window open?
one problem is, that I cannot easily / simply set it on the `send` variable, because it's shared between all tabs. Showing a toast when clicking "Save" would fix that.

**Comment by alexbarnsley** [comment]
Yeh I'm happy with a toast and leaving the window open until they resolve it 👍 this might be a good area for a few unit tests to make sure the validation continues to work, do you agree?

**Comment by Nasicus** [comment]
You mean unit tests for the urlValidateMethod or for a general validate method (which doesn't exist yet )?

**Comment by alexbarnsley** [comment]
I think the urlValidateMethod - checking if tests pass for valid URLs and invalid URLs. Well I guess you could mix them together couldn't you in some unit tests? I won't pretend I'm any good at writing tests though xD @j-a-m-l is our unit test master!

**Comment by Nasicus** [comment]
@alexbarnsley 
Check out my last commit.
Note that I used an NPM package* and the tests may be a little redundant therefore, however I find them still nice to have.
I tested only what _we_ think should be a valid URL, obviously there are a lot of other test cases which you could have.

* But Patrick, why the hell do you use an NPM package for something that simple?
Well my friends. I had the same thought. Really. I googled it and found this [post](https://stackoverflow.com/questions/5717093/check-if-a-javascript-string-is-a-url/14582229#14582229). However neither the accepted or the `138` upvoted answer work correctly 🚎

**Comment by j-a-m-l** [comment]
@Nasicus this looks good. Would you mind to resolve the conflicts?

**Comment by Nasicus** [comment]
@j-a-m-l  done

**Comment by alexbarnsley** [comment]
@Nasicus apparently `http://sdf.:3000` is a valid URL 🤔 i've not come across it in the past as valid. I had the same with `http://:3000` or `http://:`. It still fails to add the network which I'd expect, but the error message doesn't show as an invalid URL, but for "Error: Cannot connect to peer to autoconfigure the network". 
I tried adding `it('wut', () => expect(utilityService.isValidUrl('http://:3000')).to.eq(false))` as a test and the test failed, thinking it is valid. Is it just me? 😆

**Comment by Nasicus** [comment]
@alexbarnsley

Wow. Apparently not even an npm package which is only dedicated to check valid urls works correctly then.
Well I can look if I find something better when I have access to a pc again. Which will probably be on saturday.

**Comment by zillionn** [comment]
Why don't you try `input type="url"` and then `form.input.$valid` ?

**Comment by Nasicus** [comment]
Because I didn' even know that this exists ;)
Will try that - thanks.

**Comment by Nasicus** [comment]
So I added the `input type="url"` suggested by @zillionn . However this also allows some urls which are not allowed, saw that you can use `pattern` (which is a regex) to do additional validation. I used this and now _most_ (not all) invalid urls are detected.

Also reverted my other commit.

It's not perfect, but I also don't see why I or the reviewer should invest more and more time into this tbh :P

**Comment by zillionn** [comment]
> However this also allows some urls which are not allowed

For instance?

**Comment by Nasicus** [comment]
> For instance?

`fasdfsdfa:2323`  or `ftp://whatever` or `http://sdf.:3000` (however this URL is still valid even with the `pattern`)

**Comment by zillionn** [comment]
I believe they are all valid URIs:
https://tools.ietf.org/html/rfc3986#section-1.1.2

**Comment by Nasicus** [comment]
@zillionn 
Well yes probably. But not for our use case (it must always be a http / https url), hence the additional `pattern` :)

**Comment by zillionn** [comment]
OK, I'm not really sure what you're trying to do. Is this the "Seed Server" URL you're trying to validate?

**Comment by Nasicus** [comment]
Yes @zillionn  :)

**Comment by zillionn** [comment]
Alright then. Why don't you first check `form.input.$valid` and then try to access the API at `form.input.value + '/api/loader/autoconfigure'`? If the API returns JSON with `success: true`, you'll know the URL is valid.

**Comment by zillionn** [comment]
🎉

**Comment by alexbarnsley** [comment]
Hi @Nasicus. Sorry for the slow response. Also, don't kill me! I have 1 last check xD for whatever reason, putting a forward slash (/) at the end always fails. E.g. `http://107.191.39.65:4001` works, `http://107.191.39.65:4001/` doesn't. I guess here, could we get it to work with or without a forward slash. Like a browser would? 🤷‍♂️ 
I'll merge once happy with that!

**Comment by Nasicus** [comment]
done

**Comment by alexbarnsley** [comment]
Wouldn't do multiple forward slashes, but i'm happy with that as a fix 👍 thanks!

**Pull request merged**
