### PR TITLE
Improve settings menu UX

### PR DESCRIPTION
**Pull request by j-a-m-l**
Before:

settings-menu-before

After:

settings-menu-after

I've discovered that there are 2 missing translations:
- Currency
- Play song when receive funds?

### CODE REVIEW

**Comment by boldninja** [comment]
Can we change text from 'Play song when receive funds' to 'Play sound when receiving transaction?' @j-a-m-l

**Comment by j-a-m-l** [comment]
@boldninja done!

**Comment by boldninja** [comment]
song = sound  :)

**Comment by j-a-m-l** [comment]
@boldninja done ;)

**Comment by luciorubeens** [comment]
great! +5 👍🏻

**Pull request merged**
