### PR TITLE
Add total send amount in current currency selected

### PR DESCRIPTION
**Pull request by naaomimore**
A filter is just to handle empty values.

screenshot-github com-2017-05-20-11-56-55

### CODE REVIEW

**Comment by fix** [comment]
i like it
+5

**Comment by boldninja** [comment]
hi @naaomimore - you were one of the May GitHub bounty winners can you send me your permanent ARK address for this and any future rewards. Read more :

https://blog.ark.io/may-2017-github-development-winners-6526f0d78c57

**Comment by naaomimore** [comment]
yup!! please send for AWHFf3tmJLGCecWm5vZnT2rXjDa6vfqM6F. thanks

**Comment by boldninja** [comment]
@naaomimore sent : https://explorer.ark.io/tx/46a9e800a12e9e3359cff8abd426edd36df9df343ed3e3c49e2c32131a208e70 . Keep up the good work in June as well I have seen 1 commit already accepted from you in June by Fix ;).

**Comment by naaomimore** [comment]
@boldninja i have chance to win as the best quarter?

**Comment by boldninja** [comment]
Everyone from April-May-June will be eligible for 1st quarter winner, but it all depends on quality and quantity of commits.
2nd quarter winner will be for July-August-September.

**Pull request merged**
