### PR TITLE
Fix theme on qr code dialog

### PR DESCRIPTION
**Pull request by noahgr**
Hi. I noticed that in the qr code directive, the AccountController is not in scope.

Now it will follow the selected theme.

### CODE REVIEW

**Comment by luciorubeens** [comment]
+5

**Comment by boldninja** [comment]
@noahgr ARK address still the same as previous month?

**Comment by noahgr** [comment]
Yes, thank you! @boldninja

**Comment by boldninja** [comment]
Sent, keep up the good work!

**Pull request merged**
