### PR TITLE
#277 - Remove 'Sign / Verify Message' for Ledger users.

### PR DESCRIPTION
**Pull request by SBero**
#277 Check if ledgercomm is set, to determine if the 'Sign Message' tab is… displayed.

This _should_ work. I won't have a Ledger until next month to test 100%. I need someone with one  to test this.

### CODE REVIEW

**Comment by luciorubeens** [comment]
`ledgercomm` only exists in main.js

**Comment by SBero** [comment]
This should resolve that problem.

**Comment by noahgr** [comment]
Hello @sbero, sorry for the intrusion. But your solution will disable the tab for all accounts if the ledger is connected. The correct variable would be: `ul.selected.ledger`.

I hope I've helped.

**Comment by luciorubeens** [comment]
True that, good catch @noahgr. 👍🏻

Replaced manually..

+5 @SBero 
+5 @noahgr

**Comment by boldninja** [comment]
@SBero and @noahgr can you provide me with your Ark address?

**Comment by noahgr** [comment]
@boldninja AVc7bE7Ygu2E1JNrXd7skHzS3rKVBTq8jm

**Comment by boldninja** [comment]
sent - keep up the good work.

**Pull request merged**
