### PR TITLE
Select option for currency

### PR DESCRIPTION
**Pull request by SBero**
I changed the hidden currency switcher to be a select/option for an easier user experience. Now the user can very quickly change to the currency of their choice without having to potentially cycle through the entire hidden list.

### CODE REVIEW

**Comment by zillionn** [comment]
How about to move it in the settings menu below the language selection?

**Comment by luciorubeens** [comment]
@zillionn Yes, i agree. @SBero Can you move it to settings?

**Comment by SBero** [comment]
@luciorubeens Sure. I'll move it into Settings.

**Comment by SBero** [comment]
@luciorubeens Should be good to go now.

**Comment by luciorubeens** [comment]
nice! +5

**Pull request merged**
