### PR TITLE
Night/Dark Mode

### PR DESCRIPTION
**Pull request by SBero**
I've created the initial setup and implementation for dark mode #182.

An issue that does need to be considered further, is that if you use anything other the default theme you will have issues with Dark Mode.

The toggle for it can be found under the 'Settings' panel

### CODE REVIEW

**Comment by boldninja** [comment]
Just a suggestion - if you select night/dark mode 
1. It saves your current theme you had selected
2. Switches to default if not default and enables dark mode
3. If you disable it reads what you had before if it wasn't default theme

Don't know if its possible just a suggestion as I'm not a dev.

**Comment by SBero** [comment]
Good minds think alike! This is along the same lines that I was thinking was probably the best way to do it as well.

**Comment by SBero** [comment]
Ok I've updated it with a fix to allow the users theme to be stored and restored when they toggle dark mode, so that it always works now.

**Comment by luciorubeens** [comment]
Sounds good, but angular material solve this with `dark()` method. [Take a look](https://material.angularjs.org/latest/Theming/03_configuring_a_theme).

**Comment by SBero** [comment]
I've tried this with material. It's inconsistent and the dark() method doesn't seem to apply to the application properly. Some of the themes don't even do anything when called. This solution resolves it for all of the themes/styles that the user would choose.

**Comment by luciorubeens** [comment]
Fixed in e974bee51c167c582fdf4b29b90a9496990596eb

**Pull request closed without merging**
