### PR TITLE
Refresh Price

### PR DESCRIPTION
**Pull request by yagoantonio**
Refresh the price by clicking the update button on the home screen.

### CODE REVIEW

**Comment by fix** [comment]
ahah good one.
+5

**Comment by boldninja** [comment]
@yagoantonio can you provide me with your permanent ARK address where you want GitHub bounties sent? Thank you.

**Comment by yagoantonio** [comment]
Yes @boldninja tks!

AYYAeqjcZmwBzVab13REoPiZDrXtYGifQW

**Comment by boldninja** [comment]
@yagoantonio sent - keep up the good work.

**Pull request merged**
