### PR TITLE
Fixed cross-platform menu to be more consistent and bring back missing items

### PR DESCRIPTION
**Pull request by gabrielbull**
Fixed issues discussed here: #576

### CODE REVIEW

**Comment by alexbarnsley** [comment]
@gabrielbull @Nasicus both PRs looks good to me. I could do with someone with Windows to test though, or even Linux. @j-a-m-l would you mind testing on your machine, the menu options for the Ark client? See #576 for a bit more detail. If there's anyone with Windows too, but I haven't got mine at the minute
@kristjank are you able to build and test on your Windows machine?

**Comment by gabrielbull** [comment]
I have my windows machine back now, I will test this PM and fix the issues

**Comment by gabrielbull** [comment]
All fixed and tested on windows. @j-a-m-l can probably confirm it works on Linux too.

artboard

**Comment by alexbarnsley** [comment]
All working for me on Mac. @j-a-m-l are you able to confirm Linux for me please?

**Comment by j-a-m-l** [comment]
@alexbarnsley On Linux is working fine

**Comment by alexbarnsley** [comment]
Great, thanks @j-a-m-l. I'll test on Windows later and merge if all is okay :ok_hand:

**Comment by alexbarnsley** [comment]
Looking good to me! 👍

**Pull request merged**
