### PR TITLE
Refactor/add grunt dev

### PR DESCRIPTION
**Pull request by peterdouglas**
Hi team,
This PR takes the new code base and adds the grunt build/dev process to the pipeline.
This allows hot code compile and reload during the dev process, although you still need to manually reload the Electron App (CMD + R on OSX).

If you have made changes to something that is stored in local storage, you will also have to delete the local storage under the application tab.

Also, the Electron app now runs from the generated dist directory instead of the main directory.

There are several other changes I have made in here -
- Centralize node_modules to top-level directory to make managing package.json easier
- Updating COTRIBUTING.md to include new commands for dev work
- other small fixes

Thanks.

Peter 
@luciorubeens

### CODE REVIEW

**Comment by j-a-m-l** [comment]
There is an auto-reload command here: https://github.com/ArkEcosystem/ark-desktop/pull/281

**Comment by peterdouglas** [comment]
Oops, just realized that I didn't remove folders that are no longer necessary. Fixing now.

**Comment by luciorubeens** [comment]
Hey @peterdouglas, glad to see you back.. please next time make the changes separately to speed up the review.

- grunt build: I appreciate the unification of the package.json, but I'd rather have the electron load the code than it needs to compile with the grunt.
- grunt dev: the elemon package in PR made by @j-a-m-l fixed it more elegantly.
- lint: make a exclusive branch for it.

However, +5 for excluding unnecessary files.

**Comment by boldninja** [comment]
@peterdouglas can you provide me with your Ark address?

**Pull request closed without merging**
