### PR TITLE
declared increment before use to fix contact deletion bug - Resolves #333

### LINKED ISSUE #333: Unable to delete Contacts once added
After adding a contact, selecting "Remove" does nothing.

### PR DESCRIPTION
**Pull request by liamreoch**
There was a bug causing Contacts to be unable to be deleted or edited, due to an undeclared increment variable.

### CODE REVIEW

**Comment by luciorubeens** [comment]
good catch +5

**Comment by liamreoch** [comment]
thanks :)

**Comment by boldninja** [comment]
@liamreoch can you provide me your ark address :) ?

**Comment by liamreoch** [comment]
@boldninja sure can!
AJD21r5b4idabVvEPf4wAd36kmAgmoVX23

**Comment by boldninja** [comment]
sent, thanks for your work!

**Comment by liamreoch** [comment]
Thanks buddy!

**Pull request merged**
