### PR TITLE
Change price api and add more currencies

### LINKED ISSUE #221: Price API
Why you're using http://coinmarketcap.northpole.ro/ and not the official https://coinmarketcap.com/api/?

At the moment the ArkClient is showing a wrong price:
http://coinmarketcap.northpole.ro/api/v5/ARK.json - 0.000504466
https://api.coinmarketcap.com/v1/ticker/ark/ - 0.00060169

### PR DESCRIPTION
**Pull request by naaomimore**
Hi, i changed price api from [mess110/coinmarketcap.northpole.ro](https://github.com/mess110/coinmarketcap.northpole.ro) to [nexuist/coinmarketcapapi](https://github.com/Nexuist/CoinMarketCapAPI). Official coinmarketcap api doesn't have full currencies price list, only one by one. Added +20 currencies and Ark position in Market Cap.

The downside is that doesn't have the % change in 1h and 7h.

Fixes #221.

### CODE REVIEW

**Comment by luciorubeens** [comment]
sounds good, but why change api? the v8 version of current api already has 16 currencies, market cap position and last timestamp.. and we need an enhancement in symbols, maybe changing to currency code on settings. eg:

R$ = BRL

**Comment by luciorubeens** [comment]
You can use official api instead, just get with `convert` param: https://api.coinmarketcap.com/v1/ticker/ark/?convert=brl

**Comment by boldninja** [comment]
@naaomimore sent to your usual address (bounty). Keep up the good work.

**Comment by luciorubeens** [comment]
I updated the api to v8 in 300487d8d922e79012b7a5afabc27c85b67c4ef4, if you want to change to the official api please open a new PR, thank you! 👍🏻

**Pull request closed without merging**
