### PR TITLE
Moving all Ledger related requests to a fully async model

### PR DESCRIPTION
**Pull request by timart1n**
This is still a work in progress but I want to get some feedback before continuing.
All improvements are welcome as last time I did some javascript was a bunch of years ago xD.

Done:
 - ~~Ledger connection status is fully async~~
 - ~~Ledger transaction signing command is fully async~~
 - ~~Ledger get address is fully async~~
 - ~~Now a modal is shown when waiting for ledger signing command (window does not freeze so it can be moved around and can be resized, still modal blocks any user input)~~
- ~~Ledger message signing~~

TODO: 
 - Improve the modal, as currenlty is only the provided image
 - General improvements

### CODE REVIEW

**Comment by timart1n** [comment]
just FYI this is the state of the modal
image

**Comment by boldninja** [comment]
https://s1.postimg.org/45ryv4zk73/ledgernee.png

Something like this? Adding that text wrapped in <translate> tag? I don't know about text tho maybe someone can come up with something better.

**Comment by timart1n** [comment]
Hey @boldninja  @fix 
Tried to add the spinner and text to check out how it looked but to be honest I did not like it very much so I made a gif out of the image you provided just with the blue dots moving.

[gif](https://github.com/ArkEcosystem/ark-desktop/pull/324/commits/68d396274d946b8207f95bc423867b1e2f5a3178#diff-8f0b0114c7722cec67193465a711278e)

I think it looks way more professional this way ;)

Also code wise it is good to go asI believe all functionalities from ledger are async and didnt find any bugs. Still I would like to make the ledger detection a push solution as currently the render thread is polling for this every second or so :( 

Either way code review can be started as soon as I solve the merge conflicts that arrived in the meantime.

**Comment by timart1n** [comment]
@fix took a look at the conflicts and the one in account.controller.js we just accept my version as they are equivalent.
For the ledger.service.js I'm pretty sure that they are also equivalent but didn't have really the time to check thoroughly, I saw that you were the author of the previous commit, can you take a quick look. As I said I think we can just accept mine, as I believe the logic behind didn't change.

**Comment by luciorubeens** [comment]
can you review @fix? @timart1n I used but it not work properly sometimes, the ledger is not recognized if you restart the client or switch network as an example.

**Comment by timart1n** [comment]
@luciorubeens hummm, to be honest didn't test those scenarios, only tested with putting and removing the ledger. I'll try to reproduce those situations and figure out what is the problem.

**Comment by faustbrian** [comment]
@timart1n any updates on this and could you fix the conflicts?

**Comment by timart1n** [comment]
Sorry, had to be offline for quite some time.
I'll take a look into the merge conficts and then the use cases identified by @luciorubeens this weekend.

**Comment by faustbrian** [comment]
Yeah, I will close this for now.

**Pull request closed without merging**
