### PR TITLE
refactor: show pending transactions in separate table

### PR DESCRIPTION
**Pull request by goga-m**
2021-06-18-162613_1563x460_scrot

## Checklist

-   [x] My changes look good in both light AND dark mode
-   [x] The change is not hardcoded to a single network, but has multi-asset in mind
-   [x] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [x] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Comment by faustbrian** [comment]
Task linked: [CU-gx1zf5 [Wallet] Not showing pending transactions that haven't been forged yet](https://app.clickup.com/t/gx1zf5)

**Review by samharperpittam — DISMISSED** [review]
@goga-m 

It seems I have the same transaction showing in both pending and history table, is that by design?

I think each transaction should probably only exist within 1 table at a time :hmhm:

Also, I'm not sure if the 'Pending' table uses the time format setting as shown in the image below. 

image

**Comment by goga-m** [comment]
Thanks for checking it @samharperpittam!

Still a wip but yeah, the double visibility of the pending transaction is what is left to fix and the date format I think. Fixing those now and will move the clickup task for review when ready :oleglala:

**Comment by goga-m** [comment]
@samharperpittam the issues should be fixed now :+1:

**Review by faustbrian — APPROVED** [review]

**Pull request merged**
