### PR TITLE
Added ability to shift-click the currency button to have it rotate backwards

### PR DESCRIPTION
**Pull request by dunnen**
Renamed selectNextCurrency() in account.controller.js to selectCurrency().
Added tests for selectCurrency()

### CODE REVIEW

**Comment by luciorubeens** [comment]
Hey @dunnen, this is interesting but users need to know this alternative. Maybe add a hint in the tooltip.

**Comment by dunnen** [comment]
Added a tooltip. Here's a [preview](https://i.imgur.com/NG2IxTr.png) of what it looks like.

**Comment by luciorubeens** [comment]
Great, thanks! 👍🏻

**Comment by boldninja** [comment]
@dunnen  provide me with your ARK address or contact me on Ark slack (boldninja) if you don't want to share it publicly.

**Comment by dunnen** [comment]
@boldninja ADS)(=j3q

**Pull request merged**
