### PR TITLE
Add a Makefile

### PR DESCRIPTION
**Pull request by 6ea86b96**
What do you think about putting `npm` behind `make`. Makes things a little nicer IMO and could be used for building releases etc later on.

### CODE REVIEW

**Comment by Doweig** [comment]
What's wrong with npm scripts? https://github.com/ArkEcosystem/ark-desktop/issues/61
For example, to build on mac: `npm run dist:macos`

**Comment by 6ea86b96** [comment]
@Doweig it could be to do with my deep hatred for NPM and love of Make :) However, it did already simplify getting started. https://github.com/ArkEcosystem/ark-desktop/pull/63/files#diff-04c6e90faac2675aa89e2176d2eec7d8R45

**Comment by fix** [comment]
agree would be better to use a npm script instead, as make is not easily available on all platform.

I would see something like npm run install:dependencies

**Comment by fix** [comment]
closing as not usefull, since it needs to have make installed, and this cann be achieved with npm

**Pull request closed without merging**
