### PR TITLE
feat: use different transaction signing methods based on wallet import method

### PR DESCRIPTION
**Pull request by alesmit**
## Summary

https://app.clickup.com/t/jz5wn8
https://app.clickup.com/t/kbanb2

## Checklist

-   [x] Tests
-   [x] Ready to be merged

### CODE REVIEW

**Comment by faustbrian** [comment]
Task linked: [CU-kbanb2 Use import method of wallet to hide/show elements](https://app.clickup.com/t/kbanb2)

**Comment by faustbrian** [comment]
Task linked: [CU-jz5wn8 Use different transaction signing methods based on import method](https://app.clickup.com/t/jz5wn8)

**Review by samharperpittam — CHANGES_REQUESTED** [review]
So one thing i've noticed on this PR is that the task specifies that the user should be able to import via public key. But within the DW there's no option to do so. 

Is that something we can add @alesmit ?

**Comment by w3ea** [comment]
> So one thing i've noticed on this PR is that the task specifies that the user should be able to import via public key. But within the DW there's no option to do so.
> 
> Is that something we can add @alesmit ?

@samharperpittam this feature doesn't exist right now and i'll add it after this PR merged https://github.com/ArkEcosystem/desktop-wallet/pull/3814

**Pull request merged**
